# Generated by Django 5.0.6 on 2024-06-29 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0002_userprofile_is_profile_locked_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_reactions', models.PositiveIntegerField(default=0)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('total_share', models.PositiveIntegerField(default=0)),
                ('owner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='user_profile.userprofile')),
            ],
            options={
                'ordering': ['-created_at', 'total_reactions', 'total_comments', 'total_share'],
            },
        ),
    ]
