# Generated by Django 5.0.6 on 2024-06-29 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['total_reactions', 'total_comments', 'total_share', '-created_at']},
        ),
    ]
