# Generated by Django 5.0.6 on 2024-06-30 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
