# Generated by Django 5.0.6 on 2024-06-29 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0002_userprofile_is_profile_locked_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('friend_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_initiated', to='user_profile.userprofile')),
                ('friend_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to='user_profile.userprofile')),
            ],
        ),
    ]
