# Generated by Django 5.0.6 on 2024-07-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0002_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'ordering': ['-request_date']},
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('friend_one', 'friend_two')},
        ),
    ]
